### ISSUE TITLE
ReDoc examples could render more usefully

### ISSUE THREAD

**Issue by mattpolzin** [mattt/swift-package-registry-oas#2]
I've long held the opinion that ReDoc should reach into stringy examples and attempt to parse them as JSON if the type of the schema suggests it, but, since it doesn't, I've found results to be much more satisfying if examples are embedded as JSON (or YAML).

Setting aside any exception handling improprieties, here's a sketch of a solution I've adopted before:
https://github.com/mattt/swift-package-registry-oas/compare/main...mattpolzin:play-with-examples

Which produces examples in ReDoc like the one in the image I've attached.
<img width="584" alt="Screen Shot 2021-01-30 at 10 32 32 AM" src="https://user-images.githubusercontent.com/2075353/106364998-7bdd4c00-62e7-11eb-932e-74b05202b8af.png">

**Comment by mattt** [comment]
Oh wow, thanks for looking into this, @mattpolzin! I was just about to look into this exact issue. Like you, I think ReDoc should be able to intuit that examples for JSON response types are — in fact — JSON and format accordingly. Not being as familiar with this space, I wasn't entirely sure whether the fix was in OpenAPIKit, my code, or ReDoc, but thanks to you, I have my answer 😄

Working on this now, building up from your proof-of-concept in <del>#3</del><ins>#4</ins>.
